-- WARNING: This script is destructive. It drops the ANALYTICS database.

DROP DATABASE IF EXISTS ANALYTICS;
CREATE DATABASE ANALYTICS;

CREATE SCHEMA IF NOT EXISTS ANALYTICS.REF;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.SILVER;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.GOLD;
