CREATE SCHEMA IF NOT EXISTS ANALYTICS.MONITORING;

CREATE TABLE IF NOT EXISTS ANALYTICS.MONITORING.DISASTER_NAME_GROUPING_CACHE (
  record_id STRING NOT NULL,
  source_text_hash STRING NOT NULL,
  is_named_event BOOLEAN,
  canonical_event_name STRING,
  name_group STRING,
  confidence FLOAT,
  llm_model STRING,
  created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (record_id)
);
