CREATE SCHEMA IF NOT EXISTS ANALYTICS.MONITORING;

CREATE TABLE IF NOT EXISTS ANALYTICS.MONITORING.GNEWS_THEME_CACHE (
  year INTEGER NOT NULL,
  disaster_type STRING NOT NULL,
  query_hash STRING NOT NULL,
  query STRING,
  titles ARRAY,
  urls ARRAY,
  fetched_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (year, disaster_type, query_hash)
);
