-- List columns for required FEMA tables
SELECT table_name, column_name, data_type
FROM SNOWFLAKE_PUBLIC_DATA_PAID.INFORMATION_SCHEMA.COLUMNS
WHERE table_schema = 'PUBLIC_DATA'
  AND table_name IN (
    'FEMA_DISASTER_DECLARATION_INDEX',
    'FEMA_DISASTER_DECLARATION_INDEX_PIT',
    'FEMA_DISASTER_DECLARATION_AREAS_INDEX',
    'FEMA_DISASTER_DECLARATION_AREAS_INDEX_PIT',
    'FEMA_MISSION_ASSIGNMENT_INDEX',
    'FEMA_MISSION_ASSIGNMENT_INDEX_PIT',
    'FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_CLAIM_INDEX',
    'FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_CLAIM_INDEX_PIT',
    'FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_POLICY_INDEX',
    'FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_POLICY_INDEX_PIT',
    'FEMA_REGION_INDEX',
    'FEMA_REGION_INDEX_PIT'
  )
ORDER BY table_name, ordinal_position;
