-- PIT vs INDEX sanity check (row counts / latest timestamp)
SELECT
  'DECL_INDEX' AS table_name,
  COUNT(*) AS row_count
FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.FEMA_DISASTER_DECLARATION_INDEX
UNION ALL
SELECT
  'DECL_INDEX_PIT' AS table_name,
  COUNT(*) AS row_count
FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.FEMA_DISASTER_DECLARATION_INDEX_PIT;

SELECT
  'AREAS_INDEX' AS table_name,
  COUNT(*) AS row_count
FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.FEMA_DISASTER_DECLARATION_AREAS_INDEX
UNION ALL
SELECT
  'AREAS_INDEX_PIT' AS table_name,
  COUNT(*) AS row_count
FROM SNOWFLAKE_PUBLIC_DATA_PAID.PUBLIC_DATA.FEMA_DISASTER_DECLARATION_AREAS_INDEX_PIT;
